Add develop.
dmitriKrupin/java-explore-with-me pull request #1
Opened 2022-10-26 11:47 UTC by dmitriKrupin

2022-11-27 21:16 UTC, alexache requested changes

2022-11-27 21:16 UTC, alexache commented on docker-compose.yml
> +      - ewm-db
И от сервиса статистики

2022-11-27 21:16 UTC, alexache commented on main/pom.xml
> +            <version>42.3.7</version>
Версии библиотек должны быть указаны в родительском модуле через dependencyManagement

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/category/controller/AdminCategoryController.java
> +    private CategoryDto updateCategory(@Validated @RequestBody CategoryDto categoryDto) {
Здесь логичнее использовать @Valid вместо @Validated, так как не используется какая-та специальная группа валидации

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/category/mapper/CategoryMapper.java
> +        for (Category entry : categories) {
(опционально) Как-то сложно, в функциональном стиле со стримами будет попроще

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/category/model/Category.java
> +@Data
На моделях JPA не должно быть аннотаций @Data / @EqualsAndHashcode потому, что сгенерированные equals() некорректны  в случае модели

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/category/service/CategoryServiceImpl.java
> +        for (Category entry : categories) {
Точно ли нужна такая проверка еще и с полным обходом списка в Java? Если очень хочется можно сделать это одним select или count по таблице

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/category/service/CategoryServiceImpl.java
> +    public CategoryServiceImpl(CategoryRepository categoryRepository) {
@Autowired не помешает

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/compilation/service/CompilationServiceImpl.java
> +        events.remove(event);
Это не очень хороший способ через удаление по equals, лучше через removeIf и сравнение по айди

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/controller/AdminEventController.java
> +    @Autowired
Лучше делать @Autowired на конструкторе

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/controller/AdminEventController.java
> +            @RequestParam(required = false, name = "users") List<Long> users,
Для чего указывать свойство name у RequestParam, если оно сответствует имени переменной?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/controller/AdminEventController.java
> +    private List<EventFullDto> findAllEventsByParams(
Не рекомендуется делать методы контроллера приватными:
- усложняет тестирование
- они по смыслу публичные, так как доступны вовне
- запутывают других разработчиков :)

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/dto/NewEventDto.java
> +    @NotNull
Валидация отчего-то только на одно поле? Может тогда доделать и до других полей?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/repository/EventRepository.java
> +package ru.practicum.explore_with_me.event.repository;
В именах пакетов не пишутся нижние подчеркивания

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/exception/controller/ExceptionController.java
> +@Data
Зачем эта аннотация здесь?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/request/service/RequestServiceImpl.java
> +                !event.getParticipantLimit().equals(event.getViews())) {
Не очень понял это условие, как количество просмотров связано с количеством участников?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/request/service/RequestServiceImpl.java
> +            requestRepository.save(request);
А как быть с завяками на события, которые не требуют модерации?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/user/service/UserServiceImpl.java
> +        List<User> allUsersList = userRepository.findAll();
Хм, чрезвычайно сложно реализовано, почему бы не решить эту проблему одним селект запросом сс поиском по списку айди?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/user/service/UserServiceImpl.java
> +        List<User> users = userRepository.findAll();
Эту логику тоже можно реализовать оптимальнее с корректным запросом к базе по имени, хотя ограничения по имени, как мне казалось, не выдвигалось? Такие ограничения чаще делают на уровне констреинта в таблице нежели ручным поиском в логике приложения

2022-11-27 21:16 UTC, alexache commented on statistics/src/main/java/ru/practicum/explore_with_me/statistic/service/StatServiceImpl.java
> +            String start, String end, String uris, Boolean unique) {
Не вижу использования unique

2022-11-27 21:16 UTC, alexache commented on statistics/src/main/java/ru/practicum/explore_with_me/statistic/service/StatServiceImpl.java
> +        List<ViewStats> viewStatsList = new ArrayList<>();
Тоже очень сложно написано. C stats можно переделать на ViewStats через мапу URI -> количество просмотров c помощью стримов и groupingBy, например, вместо довольно сложного квадратичного обхода

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        List<Event> events = eventRepository
Не вижу использования разных видов сортировки

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        int index = response.body().indexOf("hits\":") + 6;
Почему не через полноценную десериализацию объекта?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        HttpGet someHttpGet = new HttpGet("http://localhost:9090/stats");
URI лучше задавать через проперти приложения, чтобы можно было через докер управлять ими, а не харкодить

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +            System.out.println(exception.getMessage());
Почему не через полноценный логгер?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        eventRepository.save(event);
Сохранение события через получение события довольно странный паттерн. Если это нужно из-за отображения просмотров при запросе списка событий, то лучше тамм и получать просмотры по события по списку URI

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Это очень ненадежный способ, лучше не полагатсья на такие инкременты в коде приложения. Это не будет работать с несколькими экземплярами приложения

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        if (requestLimit <= 0) {
Почему эта проверка сделана после сохранения подтержденного события?

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +
Стоит проверять предыдущие состояние заявки

2022-11-27 21:16 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        for (String entry : state) {
В функциональном стиле будет выглядеть проще

2022-12-01 13:16 UTC, dmitriKrupin commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        eventRepository.save(event);
Не совсем понял комментарий:( А как тогда сохранить то, что у события был просмотр?

2022-12-01 14:48 UTC, dmitriKrupin commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Здесь тоже не очень понятно, как исправить:(

2022-12-02 17:58 UTC, dmitriKrupin commented on main/src/main/java/ru/practicum/explore_with_me/category/mapper/CategoryMapper.java
> +        for (Category entry : categories) {
Не сказал бы, что конкретно для меня, это проще:)) Но поправил, как мог:))

2022-12-02 22:17 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        eventRepository.save(event);
Сервис статистики отвечает за хранения количества просмотров по URI

2022-12-02 22:21 UTC, alexache commented on main/src/main/java/ru/practicum/explore_with_me/event/service/EventServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Количество подтвержденных заявок можно получить в любой момент, сделав соответствующий select count(*) from event_requests where event_id=:id: and status="CONFIRMED" (псевдокод для понимания принципа)

2022-12-02 23:03 UTC, alexache requested changes

2022-12-02 23:03 UTC, alexache commented on docker-compose.yml
> +      - stats-db
(опционально) это уже излишне, сервис статистики и так зависит от запуска базы данных статистики

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/category/model/Category.java
> -@Data
@Getter @Setter не запрещены на моделях, если что

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        categories.stream()
Я не имел в виду, что нужно переделать на стрим. 
Суть в том, что ты пытаешься реализовывать фильтрацию данных на уровне Джавы, тогда как это идеальное поле для хорошего SQL запроса: boolean existsByName(String name) в *Repository например

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/compilation/controller/CompilationController.java
> +    public CompilationDto getCompilationById(@Validated @Positive @PathVariable Long compId) {
@Valid?

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        events.removeIf(id -> Objects.equals(event.getId(), eventId));
мне кажется, тут есть ошибка с используемыми параметрами
removeIf(e -> eventId.equals(e.getId())) - мне кажется такое ближе к правде

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        JsonElement jsonElement = JsonParser.parseString(response.body());
почему бы не через ObjectMapper, как в старом добром проекте таск менеджера когда-то давно?

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
>          event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Ответил на вопрос в комменте

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
>          Category category = categoryRepository.findById(event.getCategory().getId())
А зачем делать теперь эту проверку? Join не прошел бы на несуществующую категорию

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
>          request.setStatus(Status.CONFIRMED);
Все еще стоит проверить предыдущий статус заявки - что она уже не подтверждена или отменена, например

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Такого события c id " + eventId + " нет"));
Хорошо бы еще проверять, что заявки от этого юзера на это событие еще нет - иначе не допускать

2022-12-02 23:03 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +                    requestRepository.save(request);
Эти 2 строчки немного дублируются, можно бы их оставить только после условия, а setStatus(Pending) вынести в else

2022-12-02 23:03 UTC, alexache commented on statistics/src/main/resources/application.properties
> +main-server.url=http://localhost:8080
А для чего может понадобиться основной сервис?

2022-12-05 15:45 UTC, alexache requested changes

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/AddAndGetViewsForEvents.java
> +public class AddAndGetViewsForEvents {
Почему бы не сделать этот класс сервисом? Выглядит странно создание объекта данного класса вручную

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/AddAndGetViewsForEvents.java
> +                views = getViewByEventId("/events/" + entry.getId());
Запросы в цикле - это нехорошо, можно ведь передавать весь список событий, согласно API  сервиса статистики

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/compilation/mapper/CompilationMapper.java
> +            Map<Event, Long> viewsOfEvents = addAndGetViewsForEvents
Для компиляций необязательно указывать количество просмотров и заявок у событий

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        Map<Event, Long> viewsOfEvents = new AddAndGetViewsForEvents(statsPath)
Это опять же не требуется для компиляций

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/dto/EventShortDto.java
> +@EqualsAndHashCode
Эта аннотация уже включена в @Data

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
>      private Long confirmedRequests;
Это поле до сих пор считаю лишним :)

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/AddAndGetViewsForEvents.java
> +        Map<Object, Object> data = new HashMap<>();
Как-то сложно, отчего не использовать какой-нибудь простой класс, как в сервисе статистики, для представления этого

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/AddAndGetViewsForEvents.java
> +    public void addHit(String uri, String ip)
Исключения лучше отлавливать и как-то обрабатывать бы

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        Long views = 0L;
Мне кажется, просмотры и количество подтвержденных заявок нужны только для списка всех событий или для получения события по айди

2022-12-05 15:45 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +            event.setConfirmedRequests(countOfRequest);
Все еще не очень нравится такой подход с дублированием информации о количестве заявок

2022-12-07 15:32 UTC, alexache requested changes

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/service/AddAndGetViewsImpl.java
> +                if (entryFromView.getKey().equals(entryFromConfirmed.getKey().getId())) {
Зачем так сложно - к чему итерироваться если можно взять viewsOfEventsId.get(entryFromConfirmed.getKey()) - в этом же и был смысл использования словарей. К тому же весь этот метод можно было оставить в сервисе событий (тут ведь только вызов getViewsOfEventsId относится к данному сервису?

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/service/AddAndGetViewsImpl.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Можно сделать полем класса и конфигурить через либо
- бин в конфигурации и ставить @Autowired на ObjectMapper
- (нежелательно, но быстро) создавать вручную в @PostInit или в конструкторе данного класса вручную

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/common/service/AddAndGetViewsImpl.java
> +        HttpClient client = HttpClient.newHttpClient();
(опционально) Клиент тоже желательно создавать единожды

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    //@Column(name = "confirmed_requests")
Комментарии лучше подчистить

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/model/ViewsAndCountConfirmed.java
> +    Long views;
Модификаторы доступа

2022-12-07 15:32 UTC, alexache commented on main/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +            confirmedRequest = requestRepository
Это все еще запрос к базе в цикле, что недопустимо. Нужен один запрос со списком событий, как аргументом. Это конструкции в духе Long[] countByEventInAndStatus

2022-12-08 09:21 UTC, alexache approved these changes

2023-01-19 08:36 UTC, merged